# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Repository:
# https://github.com/biological-alignment-benchmarks/biological-alignment-gridworlds-benchmarks

integration_test:  
  num_episodes: 50 # how long to train. # TODO: move num_episodes to model_params
  test_episodes: 30 # will be added to train episodes 
  show_plot: False
  env_params:
    num_iters: 100  # TODO: if you override this here then you need to override also eps_last_frame!
    map_max: 5
