# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Repository:
# https://github.com/biological-alignment-benchmarks/biological-alignment-gridworlds-benchmarks

train:
  run:
    trials: 1
    episodes: 10
    steps: 10
  env_params:
    amount_agents: 1 
    scores:
        FOOD_SCORE: '{"FOOD": 10}'

test:
  run:
    test_mode: True


