experiment_1:
  timestamp: '20260126161141'
  hparams:
    params_set_title: random
    do_not_enforce_checkpoint_file_existence_during_test: true
    aggregated_results_file: outputs/random.jsonl
    agent_class: random_agent
    save_frequency: 0
    num_episodes: 0
    test_episodes: 1
